/**
 * Realistic Input Helpers
 *
 * Helpers that drive the page with input patterns that match real users:
 *   - holdKey       — OS-level autorepeat (single key held down → many `keydown`
 *                     events with `repeat=true`, NO intervening `keyup`).
 *   - typeRealistic — variable-cadence character input with occasional pauses.
 *   - pressKeysWithIME — IME composition (compositionstart / update / end +
 *                        InputEvent), as triggered by Japanese / Chinese / Korean
 *                        users.
 *
 * IMPORTANT — why CDP and not `page.evaluate(new KeyboardEvent(...))`:
 *
 * BUG-008 / BUG-009 / BUG-011 in docs/known-bugs.md prove that synthetic
 * `KeyboardEvent` objects dispatched via `dispatchEvent()` are treated
 * differently by Notion than real keystrokes. Using synthetic events in test
 * helpers would mask exactly the bug class we are trying to catch. These
 * helpers therefore route through Chrome DevTools Protocol
 * (Input.dispatchKeyEvent / Input.imeSetComposition / Input.insertText), which
 * is the same path Playwright's own `page.keyboard.*` uses and the closest
 * available approximation of real OS-level input.
 */

import type { Page, CDPSession } from "@playwright/test";

// =============================================================================
// CDP key descriptors
// =============================================================================

interface KeyDescriptor {
  code: string;
  keyCode: number;
  /** Text generated by the keystroke (empty for non-printable). */
  text: string;
}

/** Named-key descriptors. Single-character printable keys are derived. */
const NAMED_KEYS: Record<string, { code: string; keyCode: number }> = {
  ArrowUp: { code: "ArrowUp", keyCode: 38 },
  ArrowDown: { code: "ArrowDown", keyCode: 40 },
  ArrowLeft: { code: "ArrowLeft", keyCode: 37 },
  ArrowRight: { code: "ArrowRight", keyCode: 39 },
  Enter: { code: "Enter", keyCode: 13 },
  Escape: { code: "Escape", keyCode: 27 },
  Backspace: { code: "Backspace", keyCode: 8 },
  Delete: { code: "Delete", keyCode: 46 },
  Tab: { code: "Tab", keyCode: 9 },
  Space: { code: "Space", keyCode: 32 },
  Home: { code: "Home", keyCode: 36 },
  End: { code: "End", keyCode: 35 },
  PageUp: { code: "PageUp", keyCode: 33 },
  PageDown: { code: "PageDown", keyCode: 34 },
};

/**
 * Build a CDP key descriptor for a single key string. Supports:
 *   - Named keys from NAMED_KEYS
 *   - Single ASCII letters / digits
 *
 * Throws for unrecognized keys to fail loudly during test authoring rather
 * than silently dispatch a no-op event.
 */
function describeKey(key: string): KeyDescriptor {
  const named = NAMED_KEYS[key];
  if (named) {
    return { code: named.code, keyCode: named.keyCode, text: "" };
  }

  if (key.length === 1) {
    if (/[a-zA-Z]/.test(key)) {
      const upper = key.toUpperCase();
      return {
        code: `Key${upper}`,
        keyCode: upper.charCodeAt(0),
        text: key,
      };
    }
    if (/[0-9]/.test(key)) {
      return {
        code: `Digit${key}`,
        keyCode: key.charCodeAt(0),
        text: key,
      };
    }
  }

  throw new Error(
    `realistic-input: unsupported key "${key}". Add a NAMED_KEYS entry ` +
      `in test/realistic-input.ts.`,
  );
}

// =============================================================================
// CDP session caching (per page)
// =============================================================================

const cdpSessions = new WeakMap<Page, Promise<CDPSession>>();

/**
 * Get a CDPSession for the given page, caching one session per page.
 * Repeatedly calling `context.newCDPSession(page)` works but is wasteful;
 * a single session per page is sufficient for input dispatch.
 */
async function getCDP(page: Page): Promise<CDPSession> {
  let p = cdpSessions.get(page);
  if (!p) {
    p = page.context().newCDPSession(page);
    cdpSessions.set(page, p);
  }
  return p;
}

// =============================================================================
// holdKey — OS-level autorepeat simulation
// =============================================================================

export interface HoldKeyOptions {
  /** ms between consecutive autorepeat keydowns. Default 30 (typical macOS). */
  intervalMs?: number;
}

/**
 * Simulate a held key. OS-level autorepeat fires many `keydown` events with
 * `event.repeat === true` and a single trailing `keyup` — `page.keyboard.press`
 * does NOT model this (each press is a discrete down + up pair).
 *
 * Implementation: one CDP `rawKeyDown`, then `repeats - 1` autoRepeat
 * `keyDown`s with intervals, then a single `keyUp`. This matches the event
 * stream a real holding-down-j user produces.
 *
 * @param page - Playwright Page
 * @param key - Key to hold (e.g., "j", "k", "ArrowDown"). Supports named keys
 *              from NAMED_KEYS plus single ASCII letters/digits.
 * @param repeats - Total number of keydown events to dispatch (must be >= 1)
 * @param options - Optional intervalMs (default 30)
 *
 * Example:
 *   await holdKey(page, "j", 20); // hold j for 20 autorepeats
 */
export async function holdKey(
  page: Page,
  key: string,
  repeats: number,
  options: HoldKeyOptions = {},
): Promise<void> {
  if (repeats < 1) {
    throw new Error(`holdKey: repeats must be >= 1, got ${repeats}`);
  }

  const intervalMs = options.intervalMs ?? 30;
  const desc = describeKey(key);
  const cdp = await getCDP(page);

  // Initial press — rawKeyDown so that Notion's keydown listeners fire BEFORE
  // any text-insertion path that "char" would trigger.
  await cdp.send("Input.dispatchKeyEvent", {
    type: "rawKeyDown",
    key,
    code: desc.code,
    windowsVirtualKeyCode: desc.keyCode,
    nativeVirtualKeyCode: desc.keyCode,
    text: desc.text,
    unmodifiedText: desc.text,
  });

  // Autorepeat keydowns — same key, autoRepeat: true. Notion / the editor
  // sees `event.repeat === true` on these.
  for (let i = 1; i < repeats; i++) {
    await page.waitForTimeout(intervalMs);
    await cdp.send("Input.dispatchKeyEvent", {
      type: "keyDown",
      key,
      code: desc.code,
      windowsVirtualKeyCode: desc.keyCode,
      nativeVirtualKeyCode: desc.keyCode,
      text: desc.text,
      unmodifiedText: desc.text,
      autoRepeat: true,
    });
  }

  // Single keyUp at the end — that's what real autorepeat produces.
  await cdp.send("Input.dispatchKeyEvent", {
    type: "keyUp",
    key,
    code: desc.code,
    windowsVirtualKeyCode: desc.keyCode,
    nativeVirtualKeyCode: desc.keyCode,
  });
}

// =============================================================================
// typeRealistic — variable-cadence typing
// =============================================================================

export interface TypeRealisticOptions {
  /** Min ms between chars in normal cadence. Default 30. */
  minDelayMs?: number;
  /** Max ms between chars in normal cadence. Default 80. */
  maxDelayMs?: number;
  /** Probability per char of an extended pause. Default 0.1. */
  pauseProbability?: number;
  /** Min ms for an extended pause. Default 200. */
  pauseMinMs?: number;
  /** Max ms for an extended pause. Default 500. */
  pauseMaxMs?: number;
  /**
   * Optional deterministic RNG (returns [0, 1)). If omitted, uses Math.random.
   * Pass a seeded RNG for reproducible runs.
   */
  random?: () => number;
}

/**
 * Type text at realistic cadence: bursts of 30–80 ms per char with a 10%
 * chance of a 200–500 ms pause between chars (think-pauses). Uses
 * `page.keyboard.type(char)` per character so each keystroke goes through
 * Playwright's CDP-backed input pipeline (NOT synthetic KeyboardEvents).
 *
 * @param page - Playwright Page
 * @param text - Text to type
 * @param opts - Optional cadence configuration
 *
 * Example:
 *   await typeRealistic(page, "hello world");
 */
export async function typeRealistic(
  page: Page,
  text: string,
  opts: TypeRealisticOptions = {},
): Promise<void> {
  const {
    minDelayMs = 30,
    maxDelayMs = 80,
    pauseProbability = 0.1,
    pauseMinMs = 200,
    pauseMaxMs = 500,
    random = Math.random,
  } = opts;

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    await page.keyboard.type(ch);

    // No delay after the last char — caller decides what comes next.
    if (i === text.length - 1) break;

    const isPause = random() < pauseProbability;
    const delay = isPause
      ? pauseMinMs + random() * (pauseMaxMs - pauseMinMs)
      : minDelayMs + random() * (maxDelayMs - minDelayMs);
    await page.waitForTimeout(delay);
  }
}

// =============================================================================
// pressKeysWithIME — composition events
// =============================================================================

/**
 * Simulate IME (e.g., Japanese / Chinese / Korean) composition: user types
 * romaji that the IME displays as candidate text, then commits the final
 * (often non-Latin) string. The browser fires:
 *   compositionstart → compositionupdate → compositionend
 *   + InputEvent { inputType: "insertCompositionText", data: <committed> }
 *
 * Implementation: uses CDP `Input.imeSetComposition` to set candidate text,
 * then `Input.insertText` to commit. This is the same path the real Chrome
 * IME pipeline uses and triggers proper composition + InputEvent firing
 * inside the page — without requiring an actual OS IME to be installed in
 * the test environment.
 *
 * Limitations:
 *   - The candidate text shown during composition is `romaji` (this is what
 *     the page sees during `compositionupdate`). A more elaborate simulation
 *     would step through partial candidates; we keep it to a single update
 *     for simplicity.
 *   - An editable element MUST be focused before calling, otherwise CDP
 *     drops the events silently. The caller is responsible for focus.
 *   - CDP `Input.imeSetComposition` requires Chromium; will fail on other
 *     browser engines (Vimtion is Chrome-only, so this is acceptable).
 *
 * @param page - Playwright Page (must be Chromium)
 * @param romaji - The candidate text shown during composition (e.g., "nihongo")
 * @param kanji  - The committed final text (e.g., "日本語")
 *
 * Example:
 *   await page.keyboard.press("i"); // enter insert mode
 *   await pressKeysWithIME(page, "nihongo", "日本語");
 */
export async function pressKeysWithIME(
  page: Page,
  romaji: string,
  kanji: string,
): Promise<void> {
  const cdp = await getCDP(page);

  // Set candidate text — fires compositionstart + compositionupdate.
  await cdp.send("Input.imeSetComposition", {
    text: romaji,
    selectionStart: romaji.length,
    selectionEnd: romaji.length,
  });

  // Commit final text — fires compositionend + InputEvent
  // { inputType: "insertCompositionText", data: kanji }.
  await cdp.send("Input.insertText", { text: kanji });
}
